In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("train.csv")
df = df.drop(["PoolQC","Fence","MiscFeature","FireplaceQu","Alley","Id"],axis =1)

In [3]:
df["LotFrontage"] = df["LotFrontage"].fillna(df["LotFrontage"].median())
df["MasVnrType"] = df["MasVnrType"].fillna(df["MasVnrType"].mode()[0])
df["MasVnrArea"] = df["MasVnrArea"].fillna(df["MasVnrArea"].median())
df["BsmtQual"] = df["BsmtQual"].fillna(df["BsmtQual"].mode()[0])
df["BsmtCond"] = df["BsmtCond"].fillna(df["BsmtCond"].mode()[0])
df["BsmtExposure"] = df["BsmtExposure"].fillna(df["BsmtExposure"].mode()[0])
df["BsmtFinType1"] = df["BsmtFinType1"].fillna(df["BsmtFinType1"].mode()[0])
df["BsmtFinType2"] = df["BsmtFinType2"].fillna(df["BsmtFinType2"].mode()[0])
df["Electrical"] = df["Electrical"].fillna(df["Electrical"].mode()[0])
df["GarageType"] = df["GarageType"].fillna(df["GarageType"].mode()[0])
df["GarageFinish"] = df["GarageFinish"].fillna(df["GarageFinish"].mode()[0])
df["GarageQual"] = df["GarageQual"].fillna(df["GarageQual"].mode()[0])
df["GarageCond"] = df["GarageCond"].fillna(df["GarageCond"].mode()[0])
df["GarageYrBlt"] = df["GarageYrBlt"].fillna(df["GarageYrBlt"].median())    

In [4]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0          60       RL         65.0     8450   Pave      Reg         Lvl   
1          20       RL         80.0     9600   Pave      Reg         Lvl   
2          60       RL         68.0    11250   Pave      IR1         Lvl   
3          70       RL         60.0     9550   Pave      IR1         Lvl   
4          60       RL         84.0    14260   Pave      IR1         Lvl   

  Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0    AllPub    Inside       Gtl  ...             0         0           0   
1    AllPub       FR2       Gtl  ...             0         0           0   
2    AllPub    Inside       Gtl  ...             0         0           0   
3    AllPub    Corner       Gtl  ...           272         0           0   
4    AllPub       FR2       Gtl  ...             0         0           0   

  PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition SalePrice  
0        0       0       2    2008        WD         Normal    208500  
1        0       0       5    2007        WD         Normal    181500  
2        0       0       9    2008        WD         Normal    223500  
3        0       0       2    2006        WD        Abnorml    140000  
4        0       0      12    2008        WD         Normal    250000  

[5 rows x 75 columns]

In [5]:
def df_column_switch(df, column1, column2):
    i = list(df.columns)
    a, b = i.index(column1), i.index(column2)
    i[b], i[a] = i[a], i[b]
    df = df[i]
    return df

df = df_column_switch(df, "MSSubClass", "SalePrice")

In [6]:
df.head()

SalePrice MSZoning  LotFrontage  LotArea Street LotShape LandContour  \
0     208500       RL         65.0     8450   Pave      Reg         Lvl   
1     181500       RL         80.0     9600   Pave      Reg         Lvl   
2     223500       RL         68.0    11250   Pave      IR1         Lvl   
3     140000       RL         60.0     9550   Pave      IR1         Lvl   
4     250000       RL         84.0    14260   Pave      IR1         Lvl   

  Utilities LotConfig LandSlope  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0    AllPub    Inside       Gtl  ...             0         0           0   
1    AllPub       FR2       Gtl  ...             0         0           0   
2    AllPub    Inside       Gtl  ...             0         0           0   
3    AllPub    Corner       Gtl  ...           272         0           0   
4    AllPub       FR2       Gtl  ...             0         0           0   

  PoolArea MiscVal  MoSold  YrSold  SaleType  SaleCondition MSSubClass  
0        0       0       2    2008        WD         Normal         60  
1        0       0       5    2007        WD         Normal         20  
2        0       0       9    2008        WD         Normal         60  
3        0       0       2    2006        WD        Abnorml         70  
4        0       0      12    2008        WD         Normal         60  

[5 rows x 75 columns]

In [7]:
df.isnull().values.any()

False

In [8]:
df.duplicated().values.any()

False

In [9]:
categorical_features = df.select_dtypes(exclude='number')
print(categorical_features.columns)

Index(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond',
       'PavedDrive', 'SaleType', 'SaleCondition'],
      dtype='object')


In [10]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded_df = pd.DataFrame(encoder.fit_transform(df[['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities','LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2','BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st','Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation','BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2','Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual','Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond','PavedDrive', 'SaleType', 'SaleCondition']]).toarray())

In [11]:
encoded_df.head()

0    1    2    3    4    5    6    7    8    9    ...  224  225  226  227  \
0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0   
1  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0   
2  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  ...  0.0  0.0  0.0  1.0   
3  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  ...  0.0  0.0  0.0  1.0   
4  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  ...  0.0  0.0  0.0  1.0   

   228  229  230  231  232  233  
0  0.0  0.0  0.0  0.0  1.0  0.0  
1  0.0  0.0  0.0  0.0  1.0  0.0  
2  0.0  0.0  0.0  0.0  1.0  0.0  
3  1.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  1.0  0.0  

[5 rows x 234 columns]

In [12]:
df = df.join(encoded_df)

In [13]:
df.drop(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities','LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2','BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st','Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation','BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2','Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual','Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond','PavedDrive', 'SaleType', 'SaleCondition'],axis =1,inplace=True)

In [14]:
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)

In [15]:
df.head()

SalePrice  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0     208500         65.0     8450            7            5       2003   
1     181500         80.0     9600            6            8       1976   
2     223500         68.0    11250            7            5       2001   
3     140000         60.0     9550            7            5       1915   
4     250000         84.0    14260            8            5       2000   

   YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  ...  224  225  226  227  \
0          2003       196.0         706           0  ...  0.0  0.0  0.0  1.0   
1          1976         0.0         978           0  ...  0.0  0.0  0.0  1.0   
2          2002       162.0         486           0  ...  0.0  0.0  0.0  1.0   
3          1970         0.0         216           0  ...  0.0  0.0  0.0  1.0   
4          2000       350.0         655           0  ...  0.0  0.0  0.0  1.0   

   228  229  230  231  232  233  
0  0.0  0.0  0.0  0.0  1.0  0.0  
1  0.0  0.0  0.0  0.0  1.0  0.0  
2  0.0  0.0  0.0  0.0  1.0  0.0  
3  1.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  1.0  0.0  

[5 rows x 271 columns]

In [16]:
data = np.array(df)
m,n = data.shape
np.random.shuffle(data)
print(f"m:{m}")
print(f"n:{n}")

m:1460
n:271


In [17]:
val_data = data[0 : 300].T
Y_val = val_data[0]
X_val = val_data[1 : n]
X_val = X_val / 255.

train_data = data[300 : m].T
Y_train = train_data[0]
X_train = train_data[1 : n]
X_train = X_train / 255.

In [18]:
print(X_train.shape)
print(Y_train.shape)
print(X_val.shape)
print(Y_val.shape)

(270, 1160)
(1160,)
(270, 300)
(300,)


In [19]:
from src.parameter_initialization import ParameterInitialization
from src.forward_propagation import ForwardPropagation
from src.back_propagation import BackPropagation
from src.cost_function import UpdateParameters
from src.evaluation import Evaluation

In [20]:
n_classes = 1
parameter_init = ParameterInitialization(X_train.shape[0], 2, 300, n_classes)
weights, biases = parameter_init.initialize_parameters()

In [21]:
forward_propagation = ForwardPropagation()
back_propagation = BackPropagation()
update_parameters = UpdateParameters()
evaluation = Evaluation(n_classes)

In [22]:
epochs = 100
learning_rate = 0.01

In [23]:
for i in range(epochs):
    forward_output = forward_propagation.forward_propagation(weights, biases, X_train, n_classes)
    back_output = back_propagation.back_propagation_regression(forward_output, weights, X_train, Y_train, m)
    weights, biases = update_parameters.update_parameters(weights, biases, back_output, learning_rate)
    key, value = list(forward_output.items())[-1]
    if i % 10 == 0:
        print("Epoch:", i)
        print(f"Accuracy: {(evaluation.mean_squared_error(value, Y_train))*100}")
        print("~~~~~~~~~~~~~~~~~") 

[[  28844.97499783   39595.75008193   35771.49861407 ...   23250.04660602
    46225.72259715   24479.68938383]
 [ -69280.30451664  -95101.68143488  -85916.53545152 ...  -55842.31946854
  -111025.6513751   -58795.69440126]
 [  31989.68807059   43912.52528862   39671.34943149 ...   25784.79401036
    51265.30519897   27148.49388888]
 ...
 [  32491.61132271   44601.51973749   40293.79916213 ...   26189.36149587
    52069.66592452   27574.45804061]
 [  49170.78851741   67497.17250971   60978.13547891 ...   39633.35467514
    78799.00156129   41729.47384267]
 [ -54385.45582005  -74655.39203638  -67444.9971837  ...  -43836.55671745
   -87155.80423442  -46154.97380646]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[1 1 1 ... 1 1 1]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]
 ...
 [1 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]
 [1 1 1 ... 1 1 1]]
Epoch: 0
Accuracy: 3859983771982.792
~~~~~~~~~~~~~~~~~
[[3.69647033e+23 4.10772248e+23 6.22077616e+23 ... 2.34561978e+23
  4.17

/home/pranjal/Downloads/custom_neural_network_library/src/back_propagation.py:56: RuntimeWarning: invalid value encountered in multiply
  p[f"dZ{i}"] = weights[f"W{i+1}"].T.dot(p[f"dZ{i+1}"]) * activation_function.derivative_ReLU(a[f"Z{i}"])


[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
~~~~~~~~~~~~~~~~~~~~~~