In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/home/pranjal/Downloads/custom_neural_network_library/train.csv")
df = df.drop(["PoolQC","Fence","MiscFeature","FireplaceQu","Alley","Id"],axis =1)

In [3]:
df["LotFrontage"] = df["LotFrontage"].fillna(df["LotFrontage"].median())
df["MasVnrType"] = df["MasVnrType"].fillna(df["MasVnrType"].mode()[0])
df["MasVnrArea"] = df["MasVnrArea"].fillna(df["MasVnrArea"].median())
df["BsmtQual"] = df["BsmtQual"].fillna(df["BsmtQual"].mode()[0])
df["BsmtCond"] = df["BsmtCond"].fillna(df["BsmtCond"].mode()[0])
df["BsmtExposure"] = df["BsmtExposure"].fillna(df["BsmtExposure"].mode()[0])
df["BsmtFinType1"] = df["BsmtFinType1"].fillna(df["BsmtFinType1"].mode()[0])
df["BsmtFinType2"] = df["BsmtFinType2"].fillna(df["BsmtFinType2"].mode()[0])
df["Electrical"] = df["Electrical"].fillna(df["Electrical"].mode()[0])
df["GarageType"] = df["GarageType"].fillna(df["GarageType"].mode()[0])
df["GarageFinish"] = df["GarageFinish"].fillna(df["GarageFinish"].mode()[0])
df["GarageQual"] = df["GarageQual"].fillna(df["GarageQual"].mode()[0])
df["GarageCond"] = df["GarageCond"].fillna(df["GarageCond"].mode()[0])
df["GarageYrBlt"] = df["GarageYrBlt"].fillna(df["GarageYrBlt"].median())    

In [4]:
def df_column_switch(df, column1, column2):
    i = list(df.columns)
    a, b = i.index(column1), i.index(column2)
    i[b], i[a] = i[a], i[b]
    df = df[i]
    return df

df = df_column_switch(df, "MSSubClass", "SalePrice")

In [5]:
categorical_features = df.select_dtypes(exclude='number')
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded_df = pd.DataFrame(encoder.fit_transform(df[['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities','LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2','BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st','Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation','BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2','Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual','Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond','PavedDrive', 'SaleType', 'SaleCondition']]).toarray())

In [6]:
df = df.join(encoded_df)
df.drop(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities','LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2','BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st','Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation','BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2','Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual','Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond','PavedDrive', 'SaleType', 'SaleCondition'],axis =1,inplace=True)

In [7]:
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)

In [8]:
data = np.array(df)
m,n = data.shape
np.random.shuffle(data)
print(f"m:{m}")
print(f"n:{n}")

m:1460
n:271


In [9]:
val_data = data[0 : 300].T
Y_val = val_data[0]
X_val = val_data[1 : n]
X_val = X_val / 255.

train_data = data[300 : m].T
Y_train = train_data[0]
X_train = train_data[1 : n]
X_train = X_train / 255.

In [10]:
print(X_train.shape)
print(X_val.shape)
print(Y_train.shape)
print(Y_val.shape)

(270, 1160)
(270, 300)
(1160,)
(300,)


In [11]:
Y_train

array([ 84500., 335000., 274000., ..., 385000.,  84000., 135000.])

In [12]:
# import numpy as np
# import pandas as pd

def parameterss(hidden_layers, n_neurons, n_classes):
        weights = {}
        biases = {}

        for i in range(hidden_layers):

            if i == 0:
                #For the first hidden layer
                weights[f"W{i + 1}"] = np.random.rand(n_neurons, 270) - 0.5
                biases[f"b{i + 1}"] = np.random.rand(n_neurons, 1) - 0.5
            else:
                # For rest of the hidden layers
                weights[f"W{i + 1}"] = np.random.rand(n_neurons, n_neurons) - 0.5
                biases[f"b{i + 1}"] = np.random.rand(n_neurons, 1) - 0.5

        #For final output layer
        weights[f"W{hidden_layers + 1}"] = np.random.rand(n_classes, n_neurons) - 0.5
        biases[f"b{hidden_layers + 1}"] = np.random.rand(n_classes, 1) - 0.5

        return weights, biases

In [13]:
w, b = parameterss(2,300,1)

In [14]:
w.keys()

dict_keys(['W1', 'W2', 'W3'])

In [15]:
b.keys()

dict_keys(['b1', 'b2', 'b3'])

In [16]:
w['W1']

array([[-0.36598747,  0.18860181, -0.14389046, ...,  0.3458356 ,
         0.27280859, -0.45579935],
       [-0.16209191,  0.05874855, -0.06122529, ..., -0.4948456 ,
        -0.42875265, -0.27996088],
       [-0.02059145,  0.4765527 , -0.20102457, ..., -0.25481809,
         0.35821993, -0.14903044],
       ...,
       [-0.39451039, -0.07277161,  0.12503579, ...,  0.06997568,
        -0.20822434, -0.20092325],
       [ 0.42574971,  0.09723343, -0.30116852, ...,  0.14046083,
         0.32263961,  0.43103306],
       [-0.24227021,  0.32212827, -0.24530874, ..., -0.25310594,
        -0.06930676,  0.23629953]])

In [17]:
def ReLU(Z):
    return np.maximum(Z ,0)
    
def Linear(Z):
    return Z   

def derivative_ReLU(Z):
    return Z > 0

def derivative_linear(Z):
    return 1

In [18]:
def forward_propagation(weights, biases, X):
    l = len(weights)
    p = {}

    for i in range(1, l+1):
        if i == 1 :
            p[f"Z{i}"] = weights['W1'].dot(X) + biases['b1']
            p[f"A{i}"] = ReLU( weights['W1'].dot(X) + biases['b1'])
        elif i > 1 and i < l:
            p[f"Z{i}"] = weights[f"W{i}"].dot(p[f"A{i-1}"]) + biases[f"b{i}"]
            p[f"A{i}"] = ReLU(weights[f"W{i}"].dot(p[f"A{i-1}"]) + biases[f"b{i}"])
        elif i == l:
            p[f"Z{i}"] = weights[f"W{i}"].dot(p[f"A{i-1}"]) + biases[f"b{i}"]
            p[f"A{i}"] = Linear(weights[f"W{i}"].dot(p[f"A{i-1}"]) + biases[f"b{i}"])

    return p

In [19]:
a = forward_propagation(w, b, X_train)

In [20]:
a.keys()

dict_keys(['Z1', 'A1', 'Z2', 'A2', 'Z3', 'A3'])

In [21]:
def back_propagation(a, weights, X_train, Y_train):
    p = {}
    l = len(weights)

    for i in range(l, -1+1, -1):
        if i == l:
            p[f"dZ{i}"] = a[f"A{i}"] - Y_train
            p[f"dW{i}"] = 1 / m * p[f"dZ{i}"].dot(a[f"A{i-1}"].T)
            p[f"db{i}"] = 1 / m * np.sum(p[f"dZ{i}"], axis=1, keepdims=True)
        elif i < l and i > 1:
            p[f"dZ{i}"] = weights[f"W{i+1}"].T.dot(p[f"dZ{i+1}"]) * derivative_ReLU(a[f"Z{i}"])
            p[f"dW{i}"] = 1 / m * p[f"dZ{i}"].dot(a[f"A{i-1}"].T)
            p[f"db{i}"] = 1 / m * np.sum(p[f"dZ{i}"], axis=1, keepdims=True)
        elif i == 1:
            p[f"dZ{i}"] = weights[f"W{i+1}"].T.dot(p[f"dZ{i+1}"]) * derivative_linear(a[f"Z{i}"])
            p[f"dW{i}"] = 1 / m * p[f"dZ{i}"].dot(X_train.T)
            p[f"db{i}"] = 1 / m * np.sum(p[f"dZ{i}"], axis=1, keepdims=True)

    return  p

In [22]:
s = back_propagation(a, w, X_train, Y_train)

In [23]:
# l = 3
# for i in range(l,-1+1,-1):
#     print(i)

In [24]:
s.keys()

dict_keys(['dZ3', 'dW3', 'db3', 'dZ2', 'dW2', 'db2', 'dZ1', 'dW1', 'db1'])

In [25]:
def update_parameters(weights, biases, s, alpha):
    p1 = {}
    p2 = {}

    l = len(weights)

    for i in range(1, l + 1):
        p1[f"W{i}"] = weights[f"W{i}"] - alpha * s[f"dW{i}"]
        p2[f"b{i}"] = biases[f"b{i}"] - alpha * s[f"db{i}"]

    return p1, p2

In [26]:
w, b = update_parameters(w, b, s, 0.1)

In [27]:
w.keys()

dict_keys(['W1', 'W2', 'W3'])

In [28]:
b.keys()

dict_keys(['b1', 'b2', 'b3'])

In [32]:
w['W1']

array([[-8.49954871e+03, -1.26493867e+06, -7.66922975e+02, ...,
        -9.64601776e-01, -9.22767936e+01, -1.57750418e+01],
       [ 3.85006191e+03,  7.35805559e+05,  3.19847212e+02, ...,
        -2.80389879e-03,  3.82851063e+01,  5.86715957e+00],
       [-5.99475796e+03, -9.82013249e+05, -5.24083622e+02, ...,
        -1.14548231e+00, -6.14467650e+01, -1.10072102e+01],
       ...,
       [ 4.40850112e+03,  7.52221419e+05,  3.89490820e+02, ...,
         7.46519270e-01,  4.82861180e+01,  6.67289704e+00],
       [ 1.43551246e+03,  1.60769872e+05,  1.35990013e+02, ...,
         3.89867730e-01,  1.69521509e+01,  3.18287025e+00],
       [ 8.52620733e+02,  1.08892322e+05,  8.04486280e+01, ...,
        -8.71716775e-03,  9.92710190e+00,  1.47706847e+00]])

In [33]:
print(a['A3'])
print(a['A3'].shape)

[[ -85.49573834 -144.80322305 -184.34594336 ... -869.58066738
  -184.46640499 -168.1783801 ]]
(1, 1160)


In [34]:
print(Y_train)
print(Y_train.shape)

[ 84500. 335000. 274000. ... 385000.  84000. 135000.]
(1160,)


In [35]:
def mean_squared_error(Y_true, Y_pred):
    return np.mean((Y_true - Y_pred)**2)

In [36]:
last_element_key, last_element_value = list(a.items())[-1]
print(last_element_key)

A3


In [37]:
prediction = mean_squared_error(last_element_value, Y_train)

In [38]:
prediction

38769341433.868126